#pragma once

#include "esp_err.h"

#ifdef __cplusplus
extern "C" {
#endif

typedef enum {
    MOBILE_APP_COMMAND_NONE = 0,
    MOBILE_APP_COMMAND_SLEEP,
    MOBILE_APP_COMMAND_SLEPT,
    MOBILE_APP_COMMAND_STOP,
    MOBILE_APP_COMMAND_SELF_TEST,
    MOBILE_APP_COMMAND_LIGHT_RED,
    MOBILE_APP_COMMAND_LIGHT_GREEN,
    MOBILE_APP_COMMAND_LIGHT_BLUE,
    MOBILE_APP_COMMAND_LIGHT_OFF,
    MOBILE_APP_COMMAND_SCREEN_RED,
    MOBILE_APP_COMMAND_SCREEN_GREEN,
    MOBILE_APP_COMMAND_SCREEN_BLUE,
    MOBILE_APP_COMMAND_SCREEN_OFF,
    MOBILE_APP_COMMAND_AUDIO_MUSIC,
    MOBILE_APP_COMMAND_AUDIO_NOISE,
    MOBILE_APP_COMMAND_AUDIO_BREATHING,
    MOBILE_APP_COMMAND_AUDIO_VOLUME_MAX,
    MOBILE_APP_COMMAND_AUDIO_VOLUME_UP,
    MOBILE_APP_COMMAND_AUDIO_VOLUME_DOWN,
    MOBILE_APP_COMMAND_AUDIO_MUTE,
    MOBILE_APP_COMMAND_STORY,
    MOBILE_APP_COMMAND_WAKE_ACK,
    MOBILE_APP_COMMAND_SCENE_PPM,
    MOBILE_APP_COMMAND_SCENE_OCEAN,
    MOBILE_APP_COMMAND_SCENE_FOREST,
    MOBILE_APP_COMMAND_SCENE_RAIN,
    MOBILE_APP_COMMAND_SCENE_ZEN,
    MOBILE_APP_COMMAND_SCENE_EMPTY,
    MOBILE_APP_COMMAND_SCENE_PPM_PLAY,
    MOBILE_APP_COMMAND_SCENE_OCEAN_PLAY,
    MOBILE_APP_COMMAND_SCENE_FOREST_PLAY,
    MOBILE_APP_COMMAND_SCENE_RAIN_PLAY,
    MOBILE_APP_COMMAND_SCENE_ZEN_PLAY,
    MOBILE_APP_COMMAND_BREATH_RELAX,
    MOBILE_APP_COMMAND_BREATH_BOX,
    MOBILE_APP_COMMAND_BREATH_DEEP,
    MOBILE_APP_COMMAND_MID_SLEEP_TEST_MINOR,
    MOBILE_APP_COMMAND_MID_SLEEP_TEST_RESTLESS,
    MOBILE_APP_COMMAND_MID_SLEEP_TEST_AROUSAL,
    MOBILE_APP_COMMAND_MID_SLEEP_TEST_OUT_OF_BED,
    MOBILE_APP_COMMAND_LIGHT_YELLOW,
    MOBILE_APP_COMMAND_SCREEN_YELLOW,
    MOBILE_APP_COMMAND_LIGHT_BRIGHTER,
    MOBILE_APP_COMMAND_LIGHT_DIMMER,
} mobile_app_command_t;

typedef esp_err_t (*mobile_app_command_cb_t)(mobile_app_command_t command, void *ctx);

#ifdef __cplusplus
}
#endif
